markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
remote_theme: jekyll/minima

title: Jordan Beres 
description: Jordan's Website
author:
  name: Jordan Beres
  email: jordan.beres@protonmail.com
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  skin: solarized
  date_format: "%b %-d, %Y"
  
  social_links:
    - { platform: github, user_url: "https://github.com/adam-worth" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jordanberes/" }
