# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
# remote_theme: pages-themes/primer@v0.6.0
# plugins:
# - jekyll-remote-theme

# theme: minima

# name: Francisco Chiang
# title: null
#
title: Francisco Chiang
email: mail@fchiang.com
description: null
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: null
linkedin_username: fxchiang
github_username:  chicochico

# Build settings
markdown: kramdown
theme: minima
plugins: null
