markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
remote_theme: jekyll/minima

title: Francisco Chiang
author:
  name: Francisco Chiang
  email: mail@fchiang.com
description: null
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  skin: solarized
  date_format: "%b %-d, %Y"

  social_links:
    github:  chicochico
    linkedin: francisco-chiang
